#!/usr/bin/env ruby

# Copyright 2020 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See License.txt.

require 'optparse'
require 'json'

$IN = nil
$WIDTH = 256
$HEIGHT = 256
$COMPONENTS = 3
$DEPTH = 8
$OUTPUT = nil
$FORMAT = nil
parser = OptionParser.new do |opts|
  opts.summary_indent = '  '
  opts.summary_width = 30
  opts.banner = "Usage: rwimageinputgen [options]"
  opts.separator ""
  opts.separator "Options:"
  opts.on('-i', '--input SPEC', 'Specification file name.') { |f| $IN = f }
  opts.on('-w', '--width WIDTH', 'Image width.') { |w| $WIDTH = Integer(w) }
  opts.on('-h', '--height HEIGHT', 'Image height.') { |h| $HEIGHT = Integer(h) }
  opts.on('-c', '--components COMPONENTS', 'Color component count.') { |c| $COMPONENTS = Integer(c) }
  opts.on('-d', '--depth DEPTH', 'Color component bit depth.') { |d| $DEPTH = Integer(d) }
  opts.on('-f', '--filename OUTPUT', 'Image file name.') { |f| $OUTPUT = f }
  opts.on('--format FORMAT', 'Image format.') { |f| $FORMAT = f }
  opts.on('--help', 'Print this help and exit.') do
    STDOUT.puts opts
    exit 0
  end
end
parser.parse!

if $IN.nil? or $OUTPUT.nil?
  STDERR.puts '--input and --filename options must be given.'
  exit(1)
end
if $WIDTH < 1 or $HEIGHT < 1 or $COMPONENTS < 1 or $DEPTH < 1
  STDERR.puts 'Image dimensions or depth are less than 1'
  exit(1)
end

def file(val, default, mode)
  return default if val.nil?
  begin
    return File.open(val, mode)
  rescue StandardError
    STDERR.puts "Failed to open for #{mode}: #{val}"
    exit 1
  end
end

def aargh(message)
  raise ArgumentError.new(message)
end

def gen_image(width, height, components)
  img = []
  (0...height).each do |h|
    img.push([])
    (0...width).each do |w|
      img.last.push([])
      img.last.last.push((w * (width / (width - 1.0))) / width)
      img.last.last.push((h * (height / (height - 1.0))) / height) if components > 1
      img.last.last.push((w % 16 == 0) ? 1 : (h % 16 == 0) ? 1 : 0) if components > 2
      next unless components > 3
      (3...components).each do |c|
        img.last.last.push(0.5 + 0.5 * ((w * h) % c) / (c - 1))
      end
    end
  end
  return img
end

input = file($IN, STDIN, 'r')
specs = JSON.parse(input.gets(nil))

out = {}
specs.each_pair do |basename, spec|
  if basename == 'writeimage_io'
    out[basename] = { 'filename' => $OUTPUT, 'depth' => $DEPTH }
    out[basename]['format'] = $FORMAT unless $FORMAT.nil?
    out[basename]['image'] = gen_image($WIDTH, $HEIGHT, $COMPONENTS)
  elsif basename == 'readimage_io'
    out[basename] = { 'filename' => $OUTPUT, 'minimum' => 0, 'maximum' => 1 }
    out[basename]['format'] = $FORMAT unless $FORMAT.nil?
    out[basename]['shift'] = 0.25
  elsif basename == 'split2planes_io'
    out[basename] = { 'planes' => gen_image($WIDTH, $HEIGHT, $COMPONENTS) }
  end
end

out.each_pair do |basename, output|
  f = file("#{basename}.json", nil, 'wt')
  f.puts(JSON.generate(output))
  f.close()
end
